
spring:
  datasource:
    url: jdbc:h2:file:./src/main/resources/database/interstellerdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always   # Set this up in order to run the database scripts automatically on startup.
  h2:
    console:
      path: /h2
      enabled: true
      settings:
        web-allow-others: true    # H2 Console throwing a error webAllowOthers in H2 database
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
