DROP TABLE IF EXISTS PLANET;
DROP TABLE IF EXISTS ROUTES;

CREATE TABLE PLANET (
    node VARCHAR(5) DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL
);

CREATE TABLE ROUTES (
    id INT,
    planet_origin VARCHAR(5) DEFAULT NULL,
    planet_destination VARCHAR(5) DEFAULT NULL,
    distance DECIMAL DEFAULT NULL
);

ALTER TABLE ROUTES ADD FOREIGN KEY (planet_origin) REFERENCES PLANET(node);
ALTER TABLE ROUTES ADD FOREIGN KEY (planet_destination) REFERENCES PLANET(node);
