DROP TABLE IF EXISTS ROUTES;
DROP TABLE IF EXISTS PLANET;

CREATE TABLE PLANET (
    node VARCHAR(5) DEFAULT NULL PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL
);

CREATE TABLE ROUTES (
    route_id INT,
    planet_origin VARCHAR(5) DEFAULT NULL,
    planet_destination VARCHAR(5) DEFAULT NULL,
    distance_in_light_years DECIMAL DEFAULT NULL
);

ALTER TABLE ROUTES ADD FOREIGN KEY (planet_origin) REFERENCES PLANET(node);
ALTER TABLE ROUTES ADD FOREIGN KEY (planet_destination) REFERENCES PLANET(node);
